// Auto-generated by generate-aci-ts.js — do not edit manually
// Regenerate with: make generate-aci

export const DOMAIN_ROUTING_ISM_ACI = {
  contract: {
    event: {
      variant: [
        {
          IsmSet: ['int'],
        },
        {
          IsmRemoved: ['int'],
        },
        {
          DefaultIsmSet: ['address'],
        },
        {
          OwnershipTransferStarted: ['address', 'address'],
        },
        {
          OwnershipTransferred: ['address', 'address'],
        },
      ],
    },
    functions: [
      {
        arguments: [
          {
            name: 'owner',
            type: 'address',
          },
        ],
        name: 'init',
        payable: false,
        returns: 'DomainRoutingIsm.state',
        stateful: true,
      },
      {
        arguments: [],
        name: 'module_type',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'domain',
            type: 'int',
          },
          {
            name: 'ism',
            type: 'IInterchainSecurityModule',
          },
        ],
        name: 'set_ism',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'configs',
            type: {
              list: ['DomainRoutingIsm.ism_config'],
            },
          },
        ],
        name: 'set_isms',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'domain',
            type: 'int',
          },
        ],
        name: 'remove_ism',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'ism',
            type: 'IInterchainSecurityModule',
          },
        ],
        name: 'set_default_ism',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'get_domains',
        payable: false,
        returns: {
          list: ['int'],
        },
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'metadata',
            type: {
              bytes: 'any',
            },
          },
          {
            name: 'message',
            type: {
              bytes: 'any',
            },
          },
        ],
        name: 'verify',
        payable: false,
        returns: 'bool',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'message',
            type: {
              bytes: 'any',
            },
          },
        ],
        name: 'route',
        payable: false,
        returns: 'IInterchainSecurityModule',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'new_owner',
            type: 'address',
          },
        ],
        name: 'transfer_ownership',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'accept_ownership',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'get_owner',
        payable: false,
        returns: 'address',
        stateful: false,
      },
    ],
    kind: 'contract_main',
    name: 'DomainRoutingIsm',
    payable: false,
    state: {
      record: [
        {
          name: 'owner',
          type: 'address',
        },
        {
          name: 'pending_owner',
          type: {
            option: ['address'],
          },
        },
        {
          name: 'isms',
          type: {
            map: ['int', 'IInterchainSecurityModule'],
          },
        },
        {
          name: 'domains',
          type: {
            list: ['int'],
          },
        },
        {
          name: 'default_ism',
          type: {
            option: ['IInterchainSecurityModule'],
          },
        },
      ],
    },
    typedefs: [
      {
        name: 'ism_config',
        typedef: {
          record: [
            {
              name: 'domain',
              type: 'int',
            },
            {
              name: 'ism',
              type: 'IInterchainSecurityModule',
            },
          ],
        },
        vars: [],
      },
    ],
  },
};

export const IGP_ACI = {
  contract: {
    event: {
      variant: [
        {
          GasPayment: [
            {
              bytes: 32,
            },
            'int',
            'string',
            'int',
          ],
        },
        {
          BeneficiarySet: ['address'],
        },
        {
          DestinationGasOverheadSet: ['int', 'int'],
        },
      ],
    },
    functions: [
      {
        arguments: [
          {
            name: 'owner',
            type: 'address',
          },
          {
            name: 'beneficiary',
            type: 'address',
          },
          {
            name: 'oracle',
            type: 'StorageGasOracleI',
          },
        ],
        name: 'init',
        payable: false,
        returns: 'InterchainGasPaymaster.state',
        stateful: true,
      },
      {
        arguments: [],
        name: 'hook_type',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'metadata',
            type: {
              bytes: 'any',
            },
          },
          {
            name: 'message',
            type: {
              bytes: 'any',
            },
          },
        ],
        name: 'post_dispatch',
        payable: true,
        returns: 'unit',
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'metadata',
            type: {
              bytes: 'any',
            },
          },
          {
            name: 'message',
            type: {
              bytes: 'any',
            },
          },
        ],
        name: 'quote_dispatch',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'message_id',
            type: {
              bytes: 32,
            },
          },
          {
            name: 'destination',
            type: 'int',
          },
          {
            name: 'gas_limit',
            type: 'int',
          },
          {
            name: 'refund_address',
            type: 'address',
          },
        ],
        name: 'pay_for_gas',
        payable: true,
        returns: 'unit',
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'destination',
            type: 'int',
          },
          {
            name: 'gas_limit',
            type: 'int',
          },
        ],
        name: 'quote_gas_payment',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'domain',
            type: 'int',
          },
          {
            name: 'overhead',
            type: 'int',
          },
        ],
        name: 'set_destination_gas_overhead',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'configs',
            type: {
              list: ['InterchainGasPaymaster.gas_overhead_config'],
            },
          },
        ],
        name: 'set_destination_gas_overheads',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'addr',
            type: 'address',
          },
        ],
        name: 'set_beneficiary',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'claim',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'get_beneficiary',
        payable: false,
        returns: 'address',
        stateful: false,
      },
      {
        arguments: [],
        name: 'get_owner',
        payable: false,
        returns: 'address',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'domain',
            type: 'int',
          },
        ],
        name: 'destination_gas_overhead',
        payable: false,
        returns: 'int',
        stateful: false,
      },
    ],
    kind: 'contract_main',
    name: 'InterchainGasPaymaster',
    payable: false,
    state: {
      record: [
        {
          name: 'owner',
          type: 'address',
        },
        {
          name: 'beneficiary',
          type: 'address',
        },
        {
          name: 'oracle',
          type: 'StorageGasOracleI',
        },
        {
          name: 'gas_overhead',
          type: {
            map: ['int', 'int'],
          },
        },
      ],
    },
    typedefs: [
      {
        name: 'gas_overhead_config',
        typedef: {
          record: [
            {
              name: 'domain',
              type: 'int',
            },
            {
              name: 'overhead',
              type: 'int',
            },
          ],
        },
        vars: [],
      },
    ],
  },
};

export const MAILBOX_ACI = {
  contract: {
    event: {
      variant: [
        {
          Dispatch: [
            'address',
            'int',
            {
              bytes: 32,
            },
            {
              bytes: 'any',
            },
          ],
        },
        {
          DispatchId: [
            {
              bytes: 32,
            },
          ],
        },
        {
          Process: [
            'int',
            {
              bytes: 32,
            },
            'address',
          ],
        },
        {
          ProcessId: [
            {
              bytes: 32,
            },
          ],
        },
        {
          DefaultIsmSet: ['address'],
        },
        {
          DefaultHookSet: ['address'],
        },
        {
          RequiredHookSet: ['address'],
        },
      ],
    },
    functions: [
      {
        arguments: [
          {
            name: 'local_domain',
            type: 'int',
          },
          {
            name: 'owner',
            type: 'address',
          },
        ],
        name: 'init',
        payable: false,
        returns: 'Mailbox.state',
        stateful: true,
      },
      {
        arguments: [],
        name: 'version',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [],
        name: 'package_version',
        payable: false,
        returns: 'string',
        stateful: false,
      },
      {
        arguments: [],
        name: 'local_domain',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [],
        name: 'deployed_block',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [],
        name: 'nonce',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [],
        name: 'latest_dispatched_id',
        payable: false,
        returns: {
          bytes: 32,
        },
        stateful: false,
      },
      {
        arguments: [],
        name: 'default_ism',
        payable: false,
        returns: {
          option: ['IInterchainSecurityModule'],
        },
        stateful: false,
      },
      {
        arguments: [],
        name: 'default_hook',
        payable: false,
        returns: {
          option: ['IPostDispatchHook'],
        },
        stateful: false,
      },
      {
        arguments: [],
        name: 'required_hook',
        payable: false,
        returns: {
          option: ['IPostDispatchHook'],
        },
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'id',
            type: {
              bytes: 32,
            },
          },
        ],
        name: 'delivered',
        payable: false,
        returns: 'bool',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'id',
            type: {
              bytes: 32,
            },
          },
        ],
        name: 'get_delivery',
        payable: false,
        returns: {
          option: ['Mailbox.delivery'],
        },
        stateful: false,
      },
      {
        arguments: [],
        name: 'owner',
        payable: false,
        returns: 'address',
        stateful: false,
      },
      {
        arguments: [],
        name: 'pending_owner',
        payable: false,
        returns: {
          option: ['address'],
        },
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'recipient',
            type: 'address',
          },
        ],
        name: 'get_recipient_ism',
        payable: false,
        returns: {
          option: ['IInterchainSecurityModule'],
        },
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'default_ism',
            type: 'IInterchainSecurityModule',
          },
          {
            name: 'default_hook',
            type: 'IPostDispatchHook',
          },
          {
            name: 'required_hook',
            type: 'IPostDispatchHook',
          },
        ],
        name: 'initialize',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'ism',
            type: 'IInterchainSecurityModule',
          },
        ],
        name: 'set_default_ism',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'hook',
            type: 'IPostDispatchHook',
          },
        ],
        name: 'set_default_hook',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'hook',
            type: 'IPostDispatchHook',
          },
        ],
        name: 'set_required_hook',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'new_owner',
            type: 'address',
          },
        ],
        name: 'transfer_ownership',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'accept_ownership',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'renounce_ownership',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'recipient',
            type: 'address',
          },
          {
            name: 'ism',
            type: 'IInterchainSecurityModule',
          },
        ],
        name: 'set_recipient_ism',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'ism',
            type: 'IInterchainSecurityModule',
          },
        ],
        name: 'set_own_ism',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'destination_domain',
            type: 'int',
          },
          {
            name: 'recipient_address',
            type: {
              bytes: 32,
            },
          },
          {
            name: 'message_body',
            type: {
              bytes: 'any',
            },
          },
          {
            name: 'hook_metadata',
            type: {
              option: [
                {
                  bytes: 'any',
                },
              ],
            },
          },
          {
            name: 'custom_hook',
            type: {
              option: ['IPostDispatchHook'],
            },
          },
        ],
        name: 'dispatch',
        payable: true,
        returns: {
          bytes: 32,
        },
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'destination_domain',
            type: 'int',
          },
          {
            name: 'recipient_address',
            type: {
              bytes: 32,
            },
          },
          {
            name: 'message_body',
            type: {
              bytes: 'any',
            },
          },
          {
            name: 'hook_metadata',
            type: {
              option: [
                {
                  bytes: 'any',
                },
              ],
            },
          },
          {
            name: 'custom_hook',
            type: {
              option: ['IPostDispatchHook'],
            },
          },
        ],
        name: 'quote_dispatch',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'metadata',
            type: {
              bytes: 'any',
            },
          },
          {
            name: 'message',
            type: {
              bytes: 'any',
            },
          },
          {
            name: 'recipient_addr',
            type: 'address',
          },
          {
            name: 'body_recipient_addr',
            type: 'address',
          },
        ],
        name: 'process',
        payable: true,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
    ],
    kind: 'contract_main',
    name: 'Mailbox',
    payable: false,
    state: {
      record: [
        {
          name: 'owner',
          type: 'address',
        },
        {
          name: 'pending_owner',
          type: {
            option: ['address'],
          },
        },
        {
          name: 'local_domain',
          type: 'int',
        },
        {
          name: 'nonce',
          type: 'int',
        },
        {
          name: 'latest_dispatched_id',
          type: {
            bytes: 32,
          },
        },
        {
          name: 'default_ism',
          type: {
            option: ['IInterchainSecurityModule'],
          },
        },
        {
          name: 'default_hook',
          type: {
            option: ['IPostDispatchHook'],
          },
        },
        {
          name: 'required_hook',
          type: {
            option: ['IPostDispatchHook'],
          },
        },
        {
          name: 'deliveries',
          type: {
            map: [
              {
                bytes: 32,
              },
              'Mailbox.delivery',
            ],
          },
        },
        {
          name: 'recipient_isms',
          type: {
            map: ['address', 'IInterchainSecurityModule'],
          },
        },
        {
          name: 'deployed_block',
          type: 'int',
        },
        {
          name: 'initialized',
          type: 'bool',
        },
      ],
    },
    typedefs: [
      {
        name: 'delivery',
        typedef: {
          record: [
            {
              name: 'processor',
              type: 'address',
            },
            {
              name: 'block_number',
              type: 'int',
            },
          ],
        },
        vars: [],
      },
    ],
  },
};

export const MERKLE_TREE_HOOK_ACI = {
  contract: {
    event: {
      variant: [
        {
          InsertedIntoTree: [
            {
              bytes: 32,
            },
            'int',
          ],
        },
      ],
    },
    functions: [
      {
        arguments: [
          {
            name: 'mailbox',
            type: 'address',
          },
        ],
        name: 'init',
        payable: false,
        returns: 'MerkleTreeHook.state',
        stateful: true,
      },
      {
        arguments: [],
        name: 'hook_type',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [
          {
            name: '_metadata',
            type: {
              bytes: 'any',
            },
          },
          {
            name: 'message',
            type: {
              bytes: 'any',
            },
          },
        ],
        name: 'post_dispatch',
        payable: true,
        returns: 'unit',
        stateful: true,
      },
      {
        arguments: [
          {
            name: '_metadata',
            type: {
              bytes: 'any',
            },
          },
          {
            name: '_message',
            type: {
              bytes: 'any',
            },
          },
        ],
        name: 'quote_dispatch',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [],
        name: 'count',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [],
        name: 'root',
        payable: false,
        returns: {
          bytes: 32,
        },
        stateful: false,
      },
      {
        arguments: [],
        name: 'latest_checkpoint',
        payable: false,
        returns: {
          tuple: [
            {
              bytes: 32,
            },
            'int',
          ],
        },
        stateful: false,
      },
      {
        arguments: [],
        name: 'tree',
        payable: false,
        returns: 'MerkleLib.merkle_tree',
        stateful: false,
      },
      {
        arguments: [],
        name: 'get_mailbox',
        payable: false,
        returns: 'address',
        stateful: false,
      },
    ],
    kind: 'contract_main',
    name: 'MerkleTreeHook',
    payable: false,
    state: {
      record: [
        {
          name: 'mailbox',
          type: 'address',
        },
        {
          name: 'tree',
          type: 'MerkleLib.merkle_tree',
        },
      ],
    },
    typedefs: [],
  },
};

export const MULTISIG_ISM_ACI = {
  contract: {
    event: {
      variant: [
        {
          ValidatorsAndThresholdSet: ['int', 'int'],
        },
        {
          OwnershipTransferStarted: ['address', 'address'],
        },
        {
          OwnershipTransferred: ['address', 'address'],
        },
      ],
    },
    functions: [
      {
        arguments: [
          {
            name: 'owner',
            type: 'address',
          },
          {
            name: 'vals',
            type: {
              list: [
                {
                  bytes: 20,
                },
              ],
            },
          },
          {
            name: 'threshold',
            type: 'int',
          },
        ],
        name: 'init',
        payable: false,
        returns: 'MessageIdMultisigIsm.state',
        stateful: true,
      },
      {
        arguments: [],
        name: 'module_type',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'vals',
            type: {
              list: [
                {
                  bytes: 20,
                },
              ],
            },
          },
          {
            name: 'threshold',
            type: 'int',
          },
        ],
        name: 'set_validators_and_threshold',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'get_validators',
        payable: false,
        returns: {
          list: [
            {
              bytes: 20,
            },
          ],
        },
        stateful: false,
      },
      {
        arguments: [],
        name: 'get_threshold',
        payable: false,
        returns: 'int',
        stateful: false,
      },
      {
        arguments: [
          {
            name: '_message',
            type: {
              bytes: 'any',
            },
          },
        ],
        name: 'validators_and_threshold',
        payable: false,
        returns: {
          tuple: [
            {
              list: [
                {
                  bytes: 20,
                },
              ],
            },
            'int',
          ],
        },
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'new_owner',
            type: 'address',
          },
        ],
        name: 'transfer_ownership',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'accept_ownership',
        payable: false,
        returns: {
          tuple: [],
        },
        stateful: true,
      },
      {
        arguments: [],
        name: 'get_owner',
        payable: false,
        returns: 'address',
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'metadata',
            type: {
              bytes: 'any',
            },
          },
          {
            name: 'message',
            type: {
              bytes: 'any',
            },
          },
        ],
        name: 'verify',
        payable: false,
        returns: 'bool',
        stateful: false,
      },
    ],
    kind: 'contract_main',
    name: 'MessageIdMultisigIsm',
    payable: false,
    state: {
      record: [
        {
          name: 'owner',
          type: 'address',
        },
        {
          name: 'pending_owner',
          type: {
            option: ['address'],
          },
        },
        {
          name: 'validators',
          type: {
            list: [
              {
                bytes: 20,
              },
            ],
          },
        },
        {
          name: 'threshold',
          type: 'int',
        },
      ],
    },
    typedefs: [],
  },
};

export const VALIDATOR_ANNOUNCE_ACI = {
  contract: {
    event: {
      variant: [
        {
          ValidatorAnnouncement: [
            {
              bytes: 20,
            },
            'string',
          ],
        },
      ],
    },
    functions: [
      {
        arguments: [
          {
            name: 'mailbox_address',
            type: 'address',
          },
          {
            name: 'local_domain',
            type: 'int',
          },
        ],
        name: 'init',
        payable: false,
        returns: 'ValidatorAnnounce.state',
        stateful: true,
      },
      {
        arguments: [
          {
            name: 'location',
            type: 'string',
          },
        ],
        name: 'get_announcement_digest',
        payable: false,
        returns: {
          bytes: 32,
        },
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'validator',
            type: {
              bytes: 20,
            },
          },
          {
            name: 'storage_location',
            type: 'string',
          },
          {
            name: 'signature',
            type: {
              bytes: 65,
            },
          },
        ],
        name: 'announce',
        payable: false,
        returns: 'bool',
        stateful: true,
      },
      {
        arguments: [],
        name: 'get_announced_validators',
        payable: false,
        returns: {
          list: [
            {
              bytes: 20,
            },
          ],
        },
        stateful: false,
      },
      {
        arguments: [
          {
            name: 'validators',
            type: {
              list: [
                {
                  bytes: 20,
                },
              ],
            },
          },
        ],
        name: 'get_announced_storage_locations',
        payable: false,
        returns: {
          list: [
            {
              list: ['string'],
            },
          ],
        },
        stateful: false,
      },
    ],
    kind: 'contract_main',
    name: 'ValidatorAnnounce',
    payable: false,
    state: {
      record: [
        {
          name: 'mailbox_address',
          type: 'address',
        },
        {
          name: 'local_domain',
          type: 'int',
        },
        {
          name: 'announced_validators',
          type: {
            list: [
              {
                bytes: 20,
              },
            ],
          },
        },
        {
          name: 'storage_locations',
          type: {
            map: [
              {
                bytes: 20,
              },
              {
                list: ['string'],
              },
            ],
          },
        },
        {
          name: 'replay_protection',
          type: {
            map: [
              {
                bytes: 32,
              },
              'bool',
            ],
          },
        },
      ],
    },
    typedefs: [],
  },
};

// Hand-written ACI exports preserved from previous index.ts

export const NOOP_HOOK_ACI = {
  contract: {
    name: 'NoopHook',
    kind: 'contract_main',
    payable: true,
    typedefs: [],
    functions: [
      {
        name: 'hook_type',
        arguments: [],
        returns: 'int',
        stateful: false,
        payable: false,
      },
      {
        name: 'quote_dispatch',
        arguments: [
          { name: '_metadata', type: { bytes: 'any' } },
          { name: '_message', type: { bytes: 'any' } },
        ],
        returns: 'int',
        stateful: false,
        payable: false,
      },
    ],
  },
};

export const AEX9_ACI = {
  contract: {
    name: 'MintableAEX9',
    kind: 'contract_main',
    payable: false,
    typedefs: [],
    functions: [
      {
        name: 'name',
        arguments: [],
        returns: 'string',
        stateful: false,
        payable: false,
      },
      {
        name: 'symbol',
        arguments: [],
        returns: 'string',
        stateful: false,
        payable: false,
      },
      {
        name: 'decimals',
        arguments: [],
        returns: 'int',
        stateful: false,
        payable: false,
      },
      {
        name: 'total_supply',
        arguments: [],
        returns: 'int',
        stateful: false,
        payable: false,
      },
      {
        name: 'balance',
        arguments: [{ name: 'owner', type: 'address' }],
        returns: 'int',
        stateful: false,
        payable: false,
      },
      {
        name: 'allowance',
        arguments: [
          { name: 'owner', type: 'address' },
          { name: 'spender', type: 'address' },
        ],
        returns: 'int',
        stateful: false,
        payable: false,
      },
      {
        name: 'transfer',
        arguments: [
          { name: 'to', type: 'address' },
          { name: 'value', type: 'int' },
        ],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'create_allowance',
        arguments: [
          { name: 'spender', type: 'address' },
          { name: 'value', type: 'int' },
        ],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'mint',
        arguments: [
          { name: 'to', type: 'address' },
          { name: 'amount', type: 'int' },
        ],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'burn',
        arguments: [
          { name: 'from', type: 'address' },
          { name: 'amount', type: 'int' },
        ],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'get_minter',
        arguments: [],
        returns: { option: ['address'] },
        stateful: false,
        payable: false,
      },
      {
        name: 'set_minter',
        arguments: [{ name: 'minter', type: 'address' }],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
    ],
  },
};

export const WARP_ROUTER_ACI = {
  contract: {
    name: 'WarpRouter',
    kind: 'contract_main',
    payable: true,
    typedefs: [],
    functions: [
      {
        name: 'transfer_remote',
        arguments: [
          { name: 'destination', type: 'int' },
          { name: 'recipient', type: { bytes: 32 } },
          { name: 'amount', type: 'int' },
        ],
        returns: { bytes: 32 },
        stateful: true,
        payable: true,
      },
      {
        name: 'quote_transfer_remote',
        arguments: [
          { name: 'destination', type: 'int' },
          { name: 'recipient', type: { bytes: 32 } },
          { name: 'amount', type: 'int' },
        ],
        returns: 'int',
        stateful: false,
        payable: false,
      },
      {
        name: 'get_remote_router',
        arguments: [{ name: 'domain', type: 'int' }],
        returns: { option: [{ bytes: 32 }] },
        stateful: false,
        payable: false,
      },
      {
        name: 'get_destination_gas',
        arguments: [{ name: 'domain', type: 'int' }],
        returns: 'int',
        stateful: false,
        payable: false,
      },
      {
        name: 'get_decimal_scaling',
        arguments: [],
        returns: { tuple: ['int', 'int'] },
        stateful: false,
        payable: false,
      },
      {
        name: 'enroll_remote_router',
        arguments: [
          { name: 'domain', type: 'int' },
          { name: 'router', type: { bytes: 32 } },
        ],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'enroll_remote_routers',
        arguments: [
          {
            name: 'entries',
            type: { list: [{ tuple: ['int', { bytes: 32 }] }] },
          },
        ],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'get_enrolled_domains',
        arguments: [],
        returns: { list: ['int'] },
        stateful: false,
        payable: false,
      },
      {
        name: 'get_local_domain',
        arguments: [],
        returns: 'int',
        stateful: false,
        payable: false,
      },
      {
        name: 'quote_gas_payment',
        arguments: [{ name: 'domain', type: 'int' }],
        returns: 'int',
        stateful: false,
        payable: false,
      },
      {
        name: 'set_destination_gas',
        arguments: [
          { name: 'domain', type: 'int' },
          { name: 'gas', type: 'int' },
        ],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'set_destination_gas_batch',
        arguments: [
          {
            name: 'configs',
            type: { list: [{ tuple: ['int', 'int'] }] },
          },
        ],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'unenroll_remote_routers',
        arguments: [{ name: 'domains', type: { list: ['int'] } }],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'get_owner',
        arguments: [],
        returns: 'address',
        stateful: false,
        payable: false,
      },
      {
        name: 'transfer_ownership',
        arguments: [{ name: 'new_owner', type: 'address' }],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'accept_ownership',
        arguments: [],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'renounce_ownership',
        arguments: [],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'set_interchain_security_module',
        arguments: [{ name: 'ism', type: 'IInterchainSecurityModule' }],
        returns: 'unit',
        stateful: true,
        payable: false,
      },
      {
        name: 'verify_setup',
        arguments: [],
        returns: 'bool',
        stateful: false,
        payable: false,
      },
      {
        name: 'deposit',
        arguments: [],
        returns: 'unit',
        stateful: true,
        payable: true,
      },
    ],
  },
};
